### ISSUE TITLE
Module injection error on `gulp test`

### ISSUE THREAD

**Issue by sergibondarenko** [sirensolutions/kibi-wordcloud-plugin#7]
Kibi 4

I execute `gulp test --kibanahomepath=../kibi-internal` in kibi_wordcloud and I get this injection error `Error: [$injector:unpr] Unknown provider: elasticsearchPluginsProvider <- elasticsearchPlugins <- kibiState`. 

Detailed log:
```
[trex@Latitude-E5510 kibi_wordcloud_vis]$ gulp test --kibanahomepath=../kibi-internal
[14:20:50] Using gulpfile ~/Development/kibi/kibi_wordcloud_vis/gulpfile.js
[14:20:50] Starting 'sync'...
sending incremental file list
sending incremental file list
sending incremental file list
sending incremental file list

sent 63 bytes  received 12 bytes  150.00 bytes/sec
total size is 883  speedup is 11.77

sent 59 bytes  received 12 bytes  142.00 bytes/sec
total size is 255  speedup is 3.59

sent 4,877 bytes  received 51 bytes  9,856.00 bytes/sec
total size is 3,184,688  speedup is 646.24

sent 34,996 bytes  received 337 bytes  70,666.00 bytes/sec
total size is 6,360,847  speedup is 180.03
[14:20:51] Finished 'sync' after 87 ms
[14:20:51] Starting 'test'...
Running "run:testServer" (run) task
  log   [14:21:00.612] [info][optimize] Optimizing and caching bundle for tests. This may take a few minutes
  log   [14:23:24.579] [info][optimize] Optimization of bundle for tests complete in 143.96 seconds
  log   [14:23:24.584] [info] Plugin initialization disabled.
  log   [14:23:24.722] [info][listening] Server running at http://0.0.0.0:5610
Running "karma:unit" (karma) task
31 01 2017 14:23:25.201:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
31 01 2017 14:23:25.204:INFO [launcher]: Launching browser Chrome with unlimited concurrency
31 01 2017 14:23:25.212:INFO [launcher]: Starting browser Chrome
31 01 2017 14:23:26.004:INFO [Chrome 55.0.2883 (Linux 0.0.0)]: Connected on socket /#8eFYeBEcWcH5FCj8AAAA with id 2725172
Chrome 55.0.2883 (Linux 0.0.0) LOG: 'Random-ness seed: 1485869008059'

INFO: 'INFO: 2017-01-31T13:23:30Z
  Adding connection to http://localhost:9876/elasticsearch

'
INFO: 'INFO: 2017-01-31T13:23:30Z
  Adding connection to http://localhost:9876/api/saved-objects/v1

'
Chrome 55.0.2883 (Linux 0.0.0) Kibi Word Cloud Visualization "before each" hook: workFn for "creates a valid query filter" FAILED
        Error: [$injector:unpr] Unknown provider: elasticsearchPluginsProvider <- elasticsearchPlugins <- kibiState
        http://errors.angularjs.org/1.4.8/$injector/unpr?p0=elasticsearchPluginsProvider%20%3C-%20elasticsearchPlugins%20%3C-%20kibiState
            at http://localhost:5610/bundles/tests.bundle.js:28073:13
            at http://localhost:5610/bundles/tests.bundle.js:32339:20
            at Object.getService [as get] (http://localhost:5610/bundles/tests.bundle.js:32487:40)
            at http://localhost:5610/bundles/tests.bundle.js:32344:46
            at getService (http://localhost:5610/bundles/tests.bundle.js:32487:40)   
            at invoke (http://localhost:5610/bundles/tests.bundle.js:32519:14)
            at Object.instantiate (http://localhost:5610/bundles/tests.bundle.js:32536:28)
            at Object.<anonymous> (http://localhost:5610/bundles/tests.bundle.js:32396:25)
            at Object.invoke (http://localhost:5610/bundles/tests.bundle.js:32528:18)
            at Object.enforcedReturnValue [as $get] (http://localhost:5610/bundles/tests.bundle.js:32380:38)
            at Object.invoke (http://localhost:5610/bundles/tests.bundle.js:32528:18)
            at http://localhost:5610/bundles/tests.bundle.js:32345:38
            at getService (http://localhost:5610/bundles/tests.bundle.js:32487:40)   
            at Object.invoke (http://localhost:5610/bundles/tests.bundle.js:32519:14)
            at instantiate (http://localhost:5610/bundles/tests.bundle.js:61575:35)  
            at get (http://localhost:5610/bundles/tests.bundle.js:61593:23)
            at Private (http://localhost:5610/bundles/tests.bundle.js:61613:17)
            at Object.AggTypeService (http://localhost:5610/bundles/tests.bundle.js:172843:26)
            at Object.invoke (http://localhost:5610/bundles/tests.bundle.js:32528:18)
            at instantiate (http://localhost:5610/bundles/tests.bundle.js:61575:35)  
            at get (http://localhost:5610/bundles/tests.bundle.js:61593:23)
            at Private (http://localhost:5610/bundles/tests.bundle.js:61613:17)
        Error: Declaration Location
            at Object.window.inject.angular.mock.inject (http://localhost:5610/bundles/tests.bundle.js:319141:26)
            at Suite.<anonymous> (http://localhost:5610/bundles/tests.bundle.js:383473:22)
            at Object.<anonymous> (http://localhost:5610/bundles/tests.bundle.js:383456:2)
            at __webpack_require__ (http://localhost:5610/bundles/commons.bundle.js:51:30)
            at Suite.<anonymous> (http://localhost:5610/bundles/tests.bundle.js:383447:4)
            at Object.<anonymous> (http://localhost:5610/bundles/tests.bundle.js:383446:2)
            at __webpack_require__ (http://localhost:5610/bundles/commons.bundle.js:51:30)
           at Object.<anonymous> (http://localhost:5610/bundles/tests.bundle.js:485:2)
            at __webpack_require__ (http://localhost:5610/bundles/commons.bundle.js:51:30)
            at webpackJsonpCallback (http://localhost:5610/bundles/commons.bundle.js:22:20)
            at http://localhost:5610/bundles/tests.bundle.js:1:1
Chrome 55.0.2883 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.237 secs / 0.156 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.
[14:23:30] 'test' errored after 2.65 min
[14:23:30] Error: 3
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/trex/Development/kibi/kibi_wordcloud_vis/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/trex/Development/kibi/kibi_wordcloud_vis/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/trex/Development/kibi/kibi_wordcloud_vis/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/trex/Development/kibi/kibi_wordcloud_vis/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by scampi** [comment]
what version of kibi are you using ?

**Comment by sergibondarenko** [comment]
@scampi Now I run Kibi 4, kibi-internal repo, master branch.

**Comment by sergibondarenko** [comment]
Solved in this PR: https://github.com/sirensolutions/kibi_wordcloud_vis/pull/8
